#!/usr/bin/env bash
# NEON CITY STRIKE — one-shot server setup
# Run on a fresh Ubuntu/Debian VPS with a domain already pointing at it.
#
#   sudo bash setup.sh
#
# It asks for the domain and secrets, writes every config file, opens the
# firewall and starts everything. Safe to re-run: it never overwrites your
# .env, it only fills in the templates again.

set -euo pipefail
cd "$(dirname "$0")"

say() { printf '\n\033[1;36m%s\033[0m\n' "$*"; }
die() { printf '\n\033[1;31m%s\033[0m\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- 1. checks
say "1/8  checking prerequisites"
command -v docker >/dev/null || die "docker is not installed — see README step 1"
docker compose version >/dev/null 2>&1 || die "docker compose v2 is required"
[ -f game/index.html ] || die "game/index.html is missing"

# ---------------------------------------------------------------- 2. domain
if [ -z "${GAME_DOMAIN:-}" ]; then
  say "2/8  domain"
  read -rp "   your game domain (e.g. game.example.com): " GAME_DOMAIN
fi
if ! printf '%s' "$GAME_DOMAIN" | grep -q '\.'; then
  die "'$GAME_DOMAIN' does not look like a domain"
fi

# ---------------------------------------------------------------- 3. secrets
if [ ! -f .env ]; then
  say "3/8  secrets"
  if [ -z "${PEERJS_KEY:-}" ]; then
    PEERJS_KEY=$(openssl rand -base64 18 | tr -d '/+=' | head -c 24)
  fi
  if [ -z "${TURN_PASS:-}" ]; then
    TURN_PASS=$(openssl rand -base64 18 | tr -d '/+=' | head -c 24)
  fi
  TURN_USER="${TURN_USER:-ncs}"
  if [ -z "${LETSENCRYPT_EMAIL:-}" ]; then
    read -rp "   email for Let's Encrypt expiry warnings: " LETSENCRYPT_EMAIL
  fi
  cat > .env <<EOF
GAME_DOMAIN=$GAME_DOMAIN
LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
PEERJS_KEY=$PEERJS_KEY
TURN_USER=ncs
TURN_PASS=$TURN_PASS
EOF
  chmod 600 .env
  echo "   wrote .env"
else
  say "3/8  secrets — keeping your existing .env"
  # shellcheck disable=SC1091
  . ./.env
fi

# confirm the domain resolves here, otherwise certbot will fail confusingly
say "4/8  checking that $GAME_DOMAIN points at this server"
IP=$(curl -fsS "https://api.ipify.org" 2>/dev/null || hostname -I | awk '{print $1}')
DNS=$(getent hosts "$GAME_DOMAIN" 2>/dev/null | awk '{print $1}' | head -1 || true)
if [ -z "$DNS" ]; then
  die "$GAME_DOMAIN does not resolve. Add an A record for it first."
fi
if [ -n "${IP:-}" ] && [ "$DNS" != "$IP" ]; then
  printf '   warning: domain resolves to %s but this server is %s\n' "$DNS" "$IP"
  printf '   continuing anyway — fix the DNS if certificate issuance fails.\n\n'
fi

# ---------------------------------------------------------------- 5. configs
say "5/8  writing configs"
sed "s/GAME_DOMAIN_PLACEHOLDER/$GAME_DOMAIN/g" nginx.conf > nginx.conf.tmp
mv nginx.conf.tmp nginx.conf

[ -f certs ] || mkdir -p certs
sed "s/CHANGE_ME_RANDOM_PASSWORD/$TURN_PASS/g; s#CHANGE_ME_TO_YOUR_DOMAIN#$GAME_DOMAIN#g" \
  turnserver.conf > turnserver.conf.tmp
mv turnserver.conf.tmp turnserver.conf
# coturn needs the public IP; detect it when the placeholder is still there
if grep -q CHANGE_ME_TO_YOUR_PUBLIC_IP turnserver.conf; then
  PUBIP=$(curl -fsS "https://api.ipify.org" 2>/dev/null || echo "$IP")
  sed -i "s/CHANGE_ME_TO_YOUR_PUBLIC_IP/$PUBIP/g" turnserver.conf
  echo "   coturn external-ip set to $PUBIP"
fi

cat > game/ncs-config.js <<EOF
/* NEON CITY STRIKE — generated by setup.sh on $(date -u +%Y-%m-%d)
   Signalling + TURN for multiplayer. Regenerate by re-running setup.sh. */
window.NCS_CONFIG = {
  path: '/peerjs',
  key: '$PEERJS_KEY',
  secure: true,
  turnUser: '$TURN_USER',
  turnPass: '$TURN_PASS',
  iceServers: [
    { urls: ['stun:stun.l.google.com:19302', 'stun:stun.cloudflare.com:3478'] },
    { urls: 'turn:$GAME_DOMAIN:3478', username: '$TURN_USER', credential: '$TURN_PASS' }
  ]
};
EOF
echo "   wrote game/ncs-config.js"

# ---------------------------------------------------------------- 6. firewall
say "6/8  firewall"
if command -v ufw >/dev/null; then
  ufw allow 80/tcp  >/dev/null 2>&1 || true
  ufw allow 443/tcp >/dev/null 2>&1 || true
  ufw allow 3478/udp >/dev/null 2>&1 || true
  ufw allow 3478/tcp >/dev/null 2>&1 || true
  echo "   opened 80, 443, 3478 (tcp+udp)"
else
  echo "   ufw not present — open 80, 443, 3478 tcp and 3478 udp yourself"
fi

# ---------------------------------------------------------------- 7. up
say "7/8  starting containers"
docker compose up -d
echo "   waiting for the first certificate (can take a minute)..."
for i in $(seq 1 24); do
  if [ -f "certs/live/$GAME_DOMAIN/fullchain.pem" ]; then
    echo "   certificate ready"
    break
  fi
  sleep 5
  [ "$i" = 24 ] && echo "   still waiting — check: docker compose logs nginx"
done

# ---------------------------------------------------------------- 8. verify
say "8/8  verifying"
GAME="https://$GAME_DOMAIN/"
fail=0

code=$(curl -s -o /dev/null -w '%{http_code}' "$GAME" || echo 000)
if [ "$code" = 200 ]; then echo "   game page        HTTP $code  ok"; else echo "   game page        HTTP $code  FAILED"; fail=1; fi

sig=$(curl -s "https://$GAME_DOMAIN/peerjs/peerjs/js/id?key=$PEERJS_KEY" || true)
case "$sig" in
  *'"id"'*|*'"peer"'*) echo "   signalling       ok" ;;
  *) echo "   signalling       unexpected reply: ${sig:0:80}"; fail=1 ;;
esac

if docker compose ps coturn 2>/dev/null | grep -q Up; then
  echo "   TURN relay       up"
else
  echo "   TURN relay       NOT running — docker compose logs coturn"; fail=1
fi

say "done"
if [ "$fail" = 0 ]; then
  cat <<EOF

  Play:  $GAME
  Share: $GAME?room=ABCDE

  Test it properly from a phone on mobile data (not wifi) — that is the only
  way to know TURN works.

  Logs:  cd $(pwd) && docker compose logs -f
EOF
else
  echo "  something did not come up — read the messages above, then:"
  echo "  cd $(pwd) && docker compose logs --tail=60"
fi
